import 'dart:io';

import 'package:flutter/material.dart';
import 'dart:async';

import 'package:flutter_gamepad/flutter_gamepad.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<GamepadEvent> _eventLog = [];
  // Debug events are events that are generated by the gamepad but are
  // ignored because they don't map to one of our expected button/stick
  // events.
  List<GamepadEvent> _debugEventLog = [];
  StreamSubscription<GamepadEvent> _subscription;
  List<GamepadInfo> _gamepads;

  @override
  void initState() {
    super.initState();
    _subscription = FlutterGamepad.eventStream.listen(onGamepadEvent);
    // Unfortunately, can't enable debug mode until after creating the listener.
    if (Platform.isAndroid) {
      FlutterGamepad.enableDebugMode();
    }
  }

  void dispose() {
    _subscription.cancel();
    super.dispose();
  }

  String _describeEvent(GamepadEvent e) {
    if (e is GamepadConnectedEvent) {
      return 'Gamepad connected: ${e.gamepadInfo.vendorName} = ${e.gamepadId}';
    } else if (e is GamepadDisconnectedEvent) {
      return 'Gamepad disconnected: ${e.gamepadInfo.vendorName} = ${e.gamepadId}';
    } else if (e is GamepadButtonEvent) {
      return '[${e.gamepadId}] ${e.button} -> ${e.value.toStringAsFixed(3)}';
    } else if (e is GamepadThumbstickEvent) {
      return '[${e.gamepadId}] ${e.thumbstick} -> ${e.x.toStringAsFixed(3)}, ${e.y.toStringAsFixed(3)}';
    } else if (e is GamepadButtonDebugEvent) {
      return '[${e.gamepadId}] info:${e.info}';
    } else {
      return 'Unknown event: $e';
    }
  }

  String _eventLogBin(GamepadEvent e) {
    return e.runtimeType.toString() +
        (e is GamepadButtonEvent ? e.button.toString() : '') +
        (e is GamepadThumbstickEvent ? e.thumbstick.toString() : '');
  }

  void onGamepadEvent(GamepadEvent e) {
    setState(() {
      if (e is GamepadButtonDebugEvent) {
        if (_debugEventLog.isNotEmpty && _eventLogBin(e) == _eventLogBin(_debugEventLog.last)) {
          // The GamepadButtonDebugEvent is so simple that we always end up
          // just displaying the most recent event, but that works fine for now.
          _debugEventLog.removeLast();
        }
        _debugEventLog.add(e);
        if (_debugEventLog.length >= 5) _debugEventLog.removeAt(0);
      } else {
        if (_eventLog.isNotEmpty && _eventLogBin(e) == _eventLogBin(_eventLog.last)) {
          _eventLog.removeLast();
        }
        _eventLog.add(e);
        if (_eventLog.length >= (20 - _debugEventLog.length)) _eventLog.removeAt(0);
      }
    });
  }

  Future<void> _fetchGamepads() async {
    final gamepads = await FlutterGamepad.gamepads();
    setState(() {
      _gamepads = gamepads;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WillPopScope(
        onWillPop: () async => false,
        child: Scaffold(
          appBar: AppBar(
            title: const Text('Plugin example app'),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text('Running on: ${Theme.of(context).platform}\n' +
                    _eventLog.map(_describeEvent).toList().join('\n'),
                  style: TextStyle(
                    fontSize: 9.0,
                  ),
                ),
                Text('Ignored: ' +
                    _debugEventLog.map(_describeEvent).toList().join('\n'),
                  style: TextStyle(
                    fontSize: 9.0,
                  ),
                ),
                RaisedButton(onPressed: _fetchGamepads, child: Text('Call gamepads()')),
                Text('gamepads = ${_gamepads?.map((pad) => pad.vendorName)}'),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
